language: objective-c

cache:
  directories:
  - $HOME/.macports-ci-ccache

matrix:
  include:
# test all images installing in default location
  - osx_image: xcode7.3
  - osx_image: xcode8
  - osx_image: xcode8.1
  - osx_image: xcode8.2
  - osx_image: xcode8.3
  - osx_image: xcode9
  - osx_image: xcode9.1
# test all images installing in $HOME/opt
  - osx_image: xcode7.3
    env: PRE=$HOME/opt
  - osx_image: xcode8
    env: PRE=$HOME/opt
  - osx_image: xcode8.1
    env: PRE=$HOME/opt
  - osx_image: xcode8.2
    env: PRE=$HOME/opt
  - osx_image: xcode8.3
    env: PRE=$HOME/opt
  - osx_image: xcode9
    env: PRE=$HOME/opt
  - osx_image: xcode9.1
    env: PRE=$HOME/opt
# test latest image with a different sync mode
  - osx_image: xcode8.3
    env: OPT=--sync=rsync
  - osx_image: xcode8.3
    env: PRE=$HOME/opt OPT=--sync=rsync
# test latest image keeping brew in place
  - osx_image: xcode8.3
    env: OPT=--keep-brew
  - osx_image: xcode8.3
    env: PRE=$HOME/opt OPT=--keep-brew

script:
# this is required for curl to work correctly:
  - export COLUMNS=80
  - if test -z "$PRE" ; then PRE=/opt/local ; fi
  - ./macports-ci install --prefix="$PRE" $OPT
  - PATH="$PRE/bin:$PATH"
  - if test "$PRE" = /opt/local ; then ./macports-ci ccache ; fi
  - which port
# install a small port for test:
  - sudo port -N install xdrfile
  - sudo port -N uninstall xdrfile
  - ./macports-ci localports test_portfiles
# install a small local port for test:
  - sudo port -N install xdrfile1
# save ccache
  - if test "$PRE" = /opt/local ; then ./macports-ci ccache --save ; fi
