language: objective-c

cache:
  directories:
  - $HOME/.macports-ci-ccache

matrix:
  include:
# test all images installing in default location
  - osx_image: xcode6.4
  - osx_image: xcode7.3
  - osx_image: xcode8.3
  - osx_image: xcode9.4
  - osx_image: xcode10
  
script:
# this is required for curl to work correctly:
  - if !(test -z "$PRE") ; then PRE=/opt/local ; fi
  - if test "$MACPORTS_CI_EXEC" = yes ; then
      chmod +x ./macports-ci ;
      ./macports-ci install --prefix="$PRE" $OPT ;
      export COLUMNS=80 ;
      PATH="$PRE/bin:$PATH" ;
    else
      source macports-ci install --prefix="$PRE" $OPT ;
    fi
  - port installed
  - if test "$PRE" = /opt/local ; then source macports-ci ccache ; fi
# install a small port for test:
  - sudo port -N install xdrfile
  - sudo port -N uninstall xdrfile
  - source macports-ci localports test_portfiles
# install a small local port for test:
  - sudo port -N install xdrfile1
# save ccache
  - if test "$PRE" = /opt/local ; then source macports-ci ccache --save ; fi
